- name: Config poste développeur
  hosts: localhost
  become: true
  tasks:
    - name: Installer outils dev (via shell)
      shell: |
        apt-get update
        apt-get install -y docker.io git nodejs openjdk-17-jdk

    - name: Forcer changement de mot de passe
      user:
        name: dev
        expire: true


