- name: Config poste développeur
  hosts: localhost
  become: true

  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer les paquets nécessaires
      apt:
        name:
          - docker.io
          - git
          - nodejs
          - openjdk-17-jdk
        state: present

    - name: Forcer le changement de mot de passe à la prochaine connexion
      user:
        name: dev
        expire: true


