- name: Config poste développeur
  hosts: localhost
  become: true

  tasks:
    - name: Mettre à jour les paquets (via shell)
      shell: apt-get update && apt-get upgrade -y
      args:
        warn: false

    - name: Installer les paquets nécessaires (via shell)
      shell: apt-get install -y docker.io git nodejs openjdk-17-jdk
      args:
        warn: false

    - name: Forcer le changement de mot de passe à la prochaine connexion
      user:
        name: dev
        password_expire: true



