- name: Config poste développeur
  hosts: localhost
  become: true
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer outils dev (docker, git, nodejs, JDK)
      apt:
        name:
          - docker.io
          - git
          - nodejs
          - openjdk-17-jdk
        state: present

    - name: Forcer changement de mot de passe pour dev
      user:
        name: dev
        expire: true

