- name: Configuration poste secrétaire
  hosts: localhost
  become: true
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer LibreOffice
      apt:
        name: libreoffice
        state: present

    - name: Installer outils utiles
      apt:
        name:
          - firefox
          - thunderbird
          - gnome-calculator
          - evince
        state: present

    - name: Forcer changement de mot de passe
      user:
        name: secretary
        expire: true
